version: '3.5'
services:
  multipath-udp-sender:
    build:
        context: .
        dockerfile: ./Dockerfile.multipath-udp-sender
    image: ${REPOSITORY_NAME}/${PROJECT_NAME}-multipath-udp-sender:${GLOBAL_VERSION}
  nginx-rtmp-srt-transmuxer:
    build:
        context: .
        dockerfile: ./Dockerfile.nginx-rtmp-srt-transmuxer
    image: ${REPOSITORY_NAME}/${PROJECT_NAME}-nginx-rtmp-srt-transmuxer:${GLOBAL_VERSION}
  nginx-rtmp:
    build:
        context: .
        dockerfile: ./Dockerfile.nginx-rtmp
    image: ${REPOSITORY_NAME}/${PROJECT_NAME}-nginx-rtmp:${GLOBAL_VERSION}
  belabox:
    build:
        context: .
        dockerfile: ./Dockerfile.belabox
    image: ${REPOSITORY_NAME}/${PROJECT_NAME}-belabox:${GLOBAL_VERSION}