version: '3.8'
services:
  srtla:
    image: ${REPOSITORY_NAME}/srtla:${GLOBAL_VERSION}
    container_name: srtla
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports: 
      - "30000:30000/udp"
      - "8282:8282/tcp"
    volumes:
      - ./sls.conf:/etc/sls/sls.conf
  srtla-receiver:
    image: ${REPOSITORY_NAME}/${PROJECT_NAME}-belabox-srtla-receiver:${GLOBAL_VERSION}
    container_name: srtla-receiver
    restart: unless-stopped
    ports:
      - "5000:5000/udp"
      - "5001:5001/udp"
    volumes:
      - ./entrypoint.sh:/tmp/entrypoint.sh
    environment:
      - SRT_ENDPOINT_ADDR=srtla
      - SRT_ENDPOINT_PORT=30000
    depends_on:
      - "srtla"